name       : thunderbird
version    : 52.1.0
release    : 42
source     :
    - https://ftp.mozilla.org/pub/thunderbird/releases/52.1.0/source/thunderbird-52.1.0.source.tar.xz : c33ca35b6acd1a0dc0d0f4b1df16745a33144c5d3d3715fe05454a5e9eefd48b
    - https://solus-project.com/sources/mozilla/thunderbird-52.1.0-langpacks.tar.xz : f5379b28470d920b45ead9e696066c6bf8e3f05d981b42e26af1e4cd8ff9088c
license    : MPL-1.1
component  : network.mail
networking : yes
summary    : Thunderbird Email Client
description: |
    Thunderbird Email Client
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libevent)
    - pkgconfig(libffi)
    - pkgconfig(libpulse)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(pixman-1)
    - pkgconfig(sqlite3)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xt)
    - autoconf213
    - cargo
    - libjpeg-turbo-devel
    - rust
    - yasm
build      : |
    # Fedora patches
    %patch -p1 < $pkgfiles/thunderbird-install-dir.patch
    %patch -p1 < $pkgfiles/thunderbird-enable-addons.patch
    # Ported from: http://pkgs.fedoraproject.org/cgit/rpms/thunderbird.git/tree/firefox-gcc-6.0.patch
    %patch -p1 < $pkgfiles/gcc6.patch

    cp $pkgfiles/config mozconfig
    sed -i 's/##JOBCOUNT##/%JOBS%/g' mozconfig

    # GCC6 produces completely broken build
    export CFLAGS="$CFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    export CXXFLAGS="$CXXFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"

    %make -f client.mk build
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/thunderbird/extensions"
    install -D -d -m 00755 "${langpackdir}"
    
    tar xf "${sources}/thunderbird-${version}-langpacks.tar.xz"
    for i in lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -D -m 00644 "lang_pack/${lname}" "${langpackdir}"/$lname
    done
    
    %make_install -f client.mk install INSTALL_SDK= 
    mkdir -p %installroot%/usr/share/applications/
    cp $pkgfiles/thunderbird.desktop %installroot%/usr/share/applications/thunderbird.desktop
    
    # set up defaults
    install -D -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/thunderbird/defaults/pref/prefs.js

