name        : thunderbird
version     : 38.3.0
release     : 14
source      :
    - http://ftp.mozilla.org/pub/mozilla.org/thunderbird/releases/38.3.0/source/thunderbird-38.3.0.source.tar.bz2 : 9f3cb19a5ceabc5e8fa31f782b6d92720a77ef2c2d6c7b63b3d792cde491c961
license     : MPL-1.1
summary     : Thunderbird Email Client
builddeps   :
    - pkgconfig(libevent)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(x11)
    - pkgconfig(xt)
    - pkgconfig(icu-i18n)
    - pkgconfig(sqlite3)
    - pkgconfig(xcomposite)
    - libjpeg-turbo-devel
    - yasm
description : |
    Thunderbird Email Client
build      : |
    %make -f client.mk
install    : |
    %make_install -f client.mk
    mkdir -p %installroot%/usr/share/applications/
    cp $pkgfiles/config mozconfig
    sed -i 's/##JOBCOUNT##/%JOBS%/g' mozconfig
    cp $pkgfiles/thunderbird.desktop %installroot%/usr/share/applications/thunderbird.desktop
