name       : thunderbird
version    : 115.1.1
release    : 161
source     :
    - https://ftp.mozilla.org/pub/thunderbird/releases/115.1.1/source/thunderbird-115.1.1.source.tar.xz : f3255dccc2e9ffd1466f8f3404114f7c6c191f2fdbc7af3117c65fee754810b1
    - https://sources.getsol.us/mozilla/thunderbird/thunderbird-115.1.1-langpacks.tar.xz : f40b789bb64629a766fdca9ae7aa80aafe76d3aac624585572ba49274ea6d10b
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-2.0
homepage   : https://www.thunderbird.net/
component  : network.mail
clang      : yes
networking : yes
summary    : Thunderbird Email Client
description: |
    Thunderbird is a free email application that’s easy to set up and customize - and it’s loaded with great features!
builddeps  :
    - pkgconfig(alsa)
    - at-spi2-devel
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libevent)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(nss)
    - pkgconfig(xt)
    - autoconf213
    - cargo
    - cbindgen
    - dump_syms
    - llvm-clang
    - nodejs-devel
    - yasm
environment: |
    export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=system
    export MOZBUILD_STATE_PATH=$PWD
setup      : |
    cp $pkgfiles/*-api-key .
    cp $pkgfiles/config mozconfig
    sed -e 's|##JOBCOUNT##|%JOBS%|' -e 's|##LIBDIR##|%libdir%|' -e 's|##WORKDIR##|%workdir%|' -i mozconfig

    %patch -p1 < $pkgfiles/thunderbird-enable-addons.patch
    %patch -p1 < $pkgfiles/0001-Hardcode-Solus-.desktop-filename.patch
    ./mach configure
    ./mach busted
build      : |
    ./mach build
    ./mach buildsymbols
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/thunderbird/extensions"
    install -dm00755 "${langpackdir}"

    mkdir lang_pack && pushd lang_pack
    tar xf "${sources}/thunderbird-${version}-langpacks.tar.xz"

    for i in *.xpi; do
        lname="$(basename ${i})"
        install -m00644 "${lname}" "${langpackdir}/${lname}"
    done
    popd

    DESTDIR=$installdir ./mach install

    install -Dm00644 $installdir/%libdir%/thunderbird/chrome/icons/default/default256.png $installdir/usr/share/pixmaps/thunderbird.png
    for i in 16 22 24 32 48 128 256; do
        install -dm00755 $installdir/usr/share/icons/hicolor/${i}x${i}/apps
        ln -s %libdir%/thunderbird/chrome/icons/default/default${i}.png $installdir/usr/share/icons/hicolor/${i}x${i}/apps/thunderbird.png
    done
    install -Dm00644 $pkgfiles/thunderbird.desktop $installdir/usr/share/applications/net.thunderbird.Thunderbird.desktop

    # set up defaults and install appdata.xml
    install -Dm00644 $pkgfiles/prefs.js $installdir/%libdir%/thunderbird/defaults/pref/prefs.js
    install -Dm00644 $workdir/comm/mail/branding/thunderbird/net.thunderbird.Thunderbird.appdata.xml $installdir/usr/share/metainfo/net.thunderbird.Thunderbird.appdata.xml

    # Don't specify logo manually in the appdata, find it naturally through the desktop file. Fixes appstream generation
    sed -i 's|<icon type="remote" width="256" height="256">https://www.thunderbird.net/media/img/thunderbird/thunderbird-256.png</icon>||g' $installdir/usr/share/metainfo/net.thunderbird.Thunderbird.appdata.xml
