name       : thunderbird
version    : 52.6.0
release    : 52
source     :
    - https://ftp.mozilla.org/pub/thunderbird/releases/52.6.0/source/thunderbird-52.6.0.source.tar.xz : 16215fb5a3765c7e5a40eadc1f3aed6918294f6d8ef1552d2aa37656055045a8
    - https://solus-project.com/sources/mozilla/thunderbird-52.6.0-langpacks.tar.xz : 42564187989b1c6704a04a0466bbc5548a985b02f34cb61805809ab3141f2c86
license    : MPL-1.1
component  : network.mail
networking : yes
summary    : Thunderbird Email Client
description: |
    Thunderbird Email Client
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(hunspell)
    - pkgconfig(libevent)
    - pkgconfig(libffi)
    - pkgconfig(libjpeg)
    - pkgconfig(libpulse)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(pixman-1)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xt)
    - autoconf213
    - cargo
    - rust
    - yasm
optimize   :
    - no-symbolic  # Without this, the UI will be wrecked.
build      : |
    # Fedora patches
    %patch -p1 < $pkgfiles/thunderbird-install-dir.patch
    %patch -p1 < $pkgfiles/thunderbird-enable-addons.patch
    # Ported from: http://pkgs.fedoraproject.org/cgit/rpms/thunderbird.git/tree/firefox-gcc-6.0.patch
    %patch -p1 < $pkgfiles/gcc6.patch

    %patch -p0 < $pkgfiles/dont-try-to-build-mp4parse-bindings.patch

    cp $pkgfiles/config mozconfig
    sed -i 's/##JOBCOUNT##/%JOBS%/g' mozconfig

    # GCC6 produces completely broken build
    export CFLAGS="$CFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
    export CXXFLAGS="$CXXFLAGS -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"

    %make -f client.mk build
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/thunderbird/extensions"
    install -D -d -m 00755 "${langpackdir}"
    
    tar xf "${sources}/thunderbird-${version}-langpacks.tar.xz"
    for i in lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -D -m 00644 "lang_pack/${lname}" "${langpackdir}"/$lname
    done
    
    %make_install -f client.mk install INSTALL_SDK= 
    mkdir -p %installroot%/usr/share/applications/
    cp $pkgfiles/thunderbird.desktop %installroot%/usr/share/applications/thunderbird.desktop

    # set up defaults
    install -D -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/thunderbird/defaults/pref/prefs.js
