name        : thunderbird
version     : 38.6.0
release     : 21
source     :
    - https://ftp.mozilla.org/pub/thunderbird/releases/38.6.0/source/thunderbird-38.6.0.source.tar.bz2 : 0417711325a4ba6fa61882bfcd9a7ce325fa0b903474e087f16e13a70be15a6b
license     : MPL-1.1
summary     : Thunderbird Email Client
builddeps   :
    - pkgconfig(libevent)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(x11)
    - pkgconfig(xt)
    - pkgconfig(icu-i18n)
    - pkgconfig(sqlite3)
    - pkgconfig(xcomposite)
    - libjpeg-turbo-devel
    - yasm
description : |
    Thunderbird Email Client
build      : |
    cp $pkgfiles/config mozconfig
    sed -i 's/##JOBCOUNT##/%JOBS%/g' mozconfig
    %make -f client.mk
install    : |
    %make_install -f client.mk install INSTALL_SDK= 
    mkdir -p %installroot%/usr/share/applications/
    cp $pkgfiles/thunderbird.desktop %installroot%/usr/share/applications/thunderbird.desktop
