name        : thunderbird
version     : 38.7.0
release     : 22
source     :
    - https://ftp.mozilla.org/pub/thunderbird/releases/38.7.0/source/thunderbird-38.7.0.source.tar.bz2 : 1bb4b24269d8ac5b76c48c09872a2e26f6507afede234cfb6255980b149273f1
license     : MPL-1.1
summary     : Thunderbird Email Client
builddeps   :
    - pkgconfig(libevent)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(x11)
    - pkgconfig(xt)
    - pkgconfig(icu-i18n)
    - pkgconfig(sqlite3)
    - pkgconfig(xcomposite)
    - libjpeg-turbo-devel
    - yasm
description : |
    Thunderbird Email Client
build      : |
    cp $pkgfiles/config mozconfig
    sed -i 's/##JOBCOUNT##/%JOBS%/g' mozconfig
    %make -f client.mk
install    : |
    %make_install -f client.mk install INSTALL_SDK= 
    mkdir -p %installroot%/usr/share/applications/
    cp $pkgfiles/thunderbird.desktop %installroot%/usr/share/applications/thunderbird.desktop
