name        : thunderbird
version     : 38.7.2
release     : 24
source     :
    - https://ftp.mozilla.org/pub/thunderbird/releases/38.7.2/source/thunderbird-38.7.2.source.tar.bz2 : e2b1453ac193615586e350bc729278db8c8a61a8d4ac089db370754af47d4493
    - https://solus-project.com/sources/thunderbird-38.7.2-langpacks.tar.xz : 492c1a0049b324210ed9d7848161e66ca47a4e17afe0515e9f0490d953bbb07c
license     : MPL-1.1
summary     : Thunderbird Email Client
builddeps   :
    - pkgconfig(libevent)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(x11)
    - pkgconfig(xt)
    - pkgconfig(icu-i18n)
    - pkgconfig(sqlite3)
    - pkgconfig(xcomposite)
    - libjpeg-turbo-devel
    - yasm
description : |
    Thunderbird Email Client
build      : |
    # Fedora patches
    %patch -p1 < $pkgfiles/thunderbird-install-dir.patch
    %patch -p1 < $pkgfiles/thunderbird-enable-addons.patch
    
    cp $pkgfiles/config mozconfig
    sed -i 's/##JOBCOUNT##/%JOBS%/g' mozconfig
    %make -f client.mk
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/thunderbird/extensions"
    install -D -d -m 00755 "${langpackdir}"
    
    tar xf "${sources}/thunderbird-${version}-langpacks.tar.xz"
    for i in lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -D -m 00644 "lang_pack/${lname}" "${langpackdir}"/$lname
    done
    
    %make_install -f client.mk install INSTALL_SDK= 
    mkdir -p %installroot%/usr/share/applications/
    cp $pkgfiles/thunderbird.desktop %installroot%/usr/share/applications/thunderbird.desktop
    
    # set up defaults
    install -D -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/thunderbird/defaults/pref/prefs.js
