name        : thunderbird
version     : 38.5.0
release     : 17
source     :
    - https://ftp.mozilla.org/pub/thunderbird/releases/38.5.0/source/thunderbird-38.5.0.source.tar.bz2 : 7da187d4d5df17b1457bd93b584f78f5e41d2094f87c14e74ee9d8064de25d0d
license     : MPL-1.1
summary     : Thunderbird Email Client
builddeps   :
    - pkgconfig(libevent)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(x11)
    - pkgconfig(xt)
    - pkgconfig(icu-i18n)
    - pkgconfig(sqlite3)
    - pkgconfig(xcomposite)
    - libjpeg-turbo-devel
    - yasm
description : |
    Thunderbird Email Client
build      : |
    cp $pkgfiles/config mozconfig
    sed -i 's/##JOBCOUNT##/%JOBS%/g' mozconfig
    %make -f client.mk
install    : |
    %make_install -f client.mk
    mkdir -p %installroot%/usr/share/applications/
    cp $pkgfiles/thunderbird.desktop %installroot%/usr/share/applications/thunderbird.desktop
