name       : thunderbird
version    : 102.3.2
release    : 145
source     :
    - https://ftp.mozilla.org/pub/thunderbird/releases/102.3.2/source/thunderbird-102.3.2.source.tar.xz : 3e6c230e13ebc9a739821e76fd99a01f5c095b40f9f1c63a3d2d21af08b5bf33
    - https://getsol.us/sources/mozilla/thunderbird-102.3.2-langpacks.tar.xz : f5817656d60a9d4fb1608a657574273748d273247218a2907e32f8a1bcddb053
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-2.0
component  : network.mail
clang      : yes
networking : yes
summary    : Thunderbird Email Client
description: |
    Thunderbird is a free email application that’s easy to set up and customize - and it’s loaded with great features!
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gbm)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libevent)
    - pkgconfig(libffi)
    - pkgconfig(libjpeg)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(nss)
    - pkgconfig(pixman-1)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xt)
    - autoconf213
    - cargo
    - cbindgen
    - dump_syms
    - llvm-clang
    - nodejs-devel
    - yasm
environment: |
    export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=system
    export MOZBUILD_STATE_PATH=$PWD
    export LDFLAGS="${LDFLAGS/--copy-dt-needed-entries/}" # not supported by lld
setup      : |
    cp $pkgfiles/*-api-key .
    cp $pkgfiles/config mozconfig
    sed -e 's|##JOBCOUNT##|%JOBS%|' -e 's|##LIBDIR##|%libdir%|' -e 's|##WORKDIR##|%workdir%|' -i mozconfig

    %patch -p1 < $pkgfiles/thunderbird-enable-addons.patch
    %patch -p1 < $pkgfiles/cbindgen-0.24.patch
    ./mach configure
    ./mach busted
build      : |
    ./mach build
    ./mach buildsymbols
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/thunderbird/extensions"
    install -dm00755 "${langpackdir}"

    mkdir lang_pack && pushd lang_pack
    tar xf "${sources}/thunderbird-${version}-langpacks.tar.xz"

    for i in *.xpi; do
        lname="$(basename ${i})"
        install -m00644 "${lname}" "${langpackdir}/${lname}"
    done
    popd

    DESTDIR=$installdir ./mach install

    install -dm00755 $installdir/usr/share/pixmaps
    ln -s %libdir%/thunderbird/chrome/icons/default/default256.png $installdir/usr/share/pixmaps/thunderbird.png
    for i in 16 22 24 32 48 128 256; do
        install -dm00755 $installdir/usr/share/icons/hicolor/${i}x${i}
        ln -s %libdir%/thunderbird/chrome/icons/default/default${i}.png $installdir/usr/share/icons/hicolor/${i}x${i}/thunderbird.png
    done
    install -Dm00644 $pkgfiles/thunderbird.desktop $installdir/usr/share/applications/thunderbird.desktop

    # set up defaults
    install -Dm00644 $pkgfiles/prefs.js $installdir/%libdir%/thunderbird/defaults/pref/prefs.js
