name       : thunderbird
version    : 68.0
release    : 76
source     :
    - https://ftp.mozilla.org/pub/thunderbird/releases/68.0/source/thunderbird-68.0.source.tar.xz : f87dade2dd64ef61de842812d3e42d82b8a541988da851077778abfa2ebd95d1
    - https://getsol.us/sources/mozilla/thunderbird-68.0-langpacks.tar.xz : d818b66feb9a0c362c81f81dbc9bc8e7e04481944ff74e465719dfa5341323ae
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-2.0
component  : network.mail
clang      : yes
networking : yes
summary    : Thunderbird Email Client
description: |
    Thunderbird is a free email application that’s easy to set up and customize - and it’s loaded with great features!
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libevent)
    - pkgconfig(libffi)
    - pkgconfig(libjpeg)
    - pkgconfig(libpulse)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(nss)
    - pkgconfig(pixman-1)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xt)
    - autoconf213
    - cargo
    - cbindgen
    - llvm-clang
    - nodejs-devel
    - yasm
setup      : |
    cp $pkgfiles/mozilla-api-key .
    cp $pkgfiles/config mozconfig
    sed -e 's|##JOBCOUNT##|%JOBS%|' -e 's|##LIBDIR##|%libdir%|' -i mozconfig

    %patch -p1 < $pkgfiles/thunderbird-enable-addons.patch

    ./mach configure
build      : |
    ./mach build
    ./mach buildsymbols
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/thunderbird/extensions"
    install -dm00755 "${langpackdir}"

    mkdir lang_pack && pushd lang_pack
    tar xf "${sources}/thunderbird-${version}-langpacks.tar.xz"

    for i in *.xpi; do
        lname="$(basename ${i})"
        install -m00644 "${lname}" "${langpackdir}/${lname}"
    done
    popd

    DESTDIR=$installdir ./mach install

    install -dm00755 $installdir/usr/share/pixmaps
    ln -s %libdir%/thunderbird/chrome/icons/default/default256.png $installdir/usr/share/pixmaps/thunderbird.png
    for i in 16 22 24 32 48 128 256; do
        install -dm00755 $installdir/usr/share/icons/hicolor/${i}x${i}
        ln -s %libdir%/thunderbird/chrome/icons/default/default${i}.png $installdir/usr/share/icons/hicolor/${i}x${i}/thunderbird.png
    done
    install -Dm00644 $pkgfiles/thunderbird.desktop $installdir/usr/share/applications/thunderbird.desktop

    # set up defaults
    install -Dm00644 $pkgfiles/prefs.js $installdir/%libdir%/thunderbird/defaults/pref/prefs.js
