name        : thunderbird
version     : 45.2.0
release     : 27
source     :
    - https://ftp.mozilla.org/pub/thunderbird/releases/45.2.0/source/thunderbird-45.2.0.source.tar.xz : bd2389cbb28138668ab41b26f1dce49c455807e09b43fd370ee765ae3f0937c0
    - https://solus-project.com/sources/thunderbird-45.2.0-langpacks.tar.xz : b5fd54505dae76e35e951f46d64273a9327cbd933dbbafff27734c253a355043
license     : MPL-1.1
summary     : Thunderbird Email Client
builddeps   :
    - pkgconfig(libevent)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(x11)
    - pkgconfig(xt)
    - pkgconfig(icu-i18n)
    - pkgconfig(sqlite3)
    - pkgconfig(gconf-2.0)
    - pkgconfig(xcomposite)
    - libjpeg-turbo-devel
    - yasm
description : |
    Thunderbird Email Client
build      : |
    # Fedora patches
    %patch -p1 < $pkgfiles/thunderbird-install-dir.patch
    %patch -p1 < $pkgfiles/thunderbird-enable-addons.patch
    
    cp $pkgfiles/config mozconfig
    sed -i 's/##JOBCOUNT##/%JOBS%/g' mozconfig
    %make -f client.mk
install    : |
    # Install locales first
    langpackdir="$installdir/%libdir%/thunderbird/extensions"
    install -D -d -m 00755 "${langpackdir}"
    
    tar xf "${sources}/thunderbird-${version}-langpacks.tar.xz"
    for i in lang_pack/*.xpi; do
        lname="$(basename ${i})"
        install -D -m 00644 "lang_pack/${lname}" "${langpackdir}"/$lname
    done
    
    %make_install -f client.mk install INSTALL_SDK= 
    mkdir -p %installroot%/usr/share/applications/
    cp $pkgfiles/thunderbird.desktop %installroot%/usr/share/applications/thunderbird.desktop
    
    # set up defaults
    install -D -m 00644 $pkgfiles/prefs.js $installdir/%libdir%/thunderbird/defaults/pref/prefs.js
